### ISSUE TITLE
Lock Opened on its own without any planned action for open either on time or through the dashboard

### ISSUE THREAD

**Issue by macdenewf** [joelwetzel/Hubitat-Reliable-Locks#1]
Hi.  something odd happened yesterday.
When i posted this on the HE community someone suggested that Reliable Locks may have sent an unlock command to a lock of mine due to an unresolved state.
Was hoping someone might be able to identify the source of an unplanned open at my lock.
Please let me know if there is any additional info required.

Description of the problem

I have 3 Kwikset locks in my home. I have them paired to HE with rules set up to lock at 3 specific times throughout the evening / night.

I do have some other integrations with the locks ( Echo Skill / Sharp Tools / Fabriq / Sonos) but those are for notifications and dashboard control.....no commands are pre set for open.

This morning i manually unlocked my lock to have my coffee on the patio. Cant say i specifically recall manually locking it when i came back in ...but it is a habit so i will have to assume i did.
A few minutes after i came back inside - i heard the lock activate. When i physically checked the status - the lock was open. I checked my rules and i have nothing for this time of the day to unlock..rather i dont have any rule that unlocks my door..only rules to lock the door.

I also have the reliable user app installed...but only use that on my dashboard for accurate status updates.
Really would appreciate if anyone can point out what i should be looking for.

8:33..seems right for me manually unlocking the door
I don't see an entry for manually locking the door...but the fact i heard it operate shortly after leads me to believe i must have
8:56....the patio door unlocked without command.
I dont mind a glitch in the vast majority of my automations and rules. If lights go on or off when not scheduled...no big deal....but a lock opening on its own...would really like to sort that one.

Appreciate any thoughts. I hate the idea of having a lock open unintended.
Thanks
mac

![Screen Shot 2020-10-18 at 9 29 51 AM](https://user-images.githubusercontent.com/73120647/96462618-61291080-11eb-11eb-93e4-8b27bb9d688d.png)

![Screen Shot 2020-10-18 at 9 15 59 AM](https://user-images.githubusercontent.com/73120647/96462675-700fc300-11eb-11eb-9b0c-7955446df9f8.png)

![Screen Shot 2020-10-18 at 8 57 23 AM](https://user-images.githubusercontent.com/73120647/96462687-7605a400-11eb-11eb-828f-237ba10d5cf9.png)

![Screen Shot 2020-10-18 at 9 16 52 AM](https://user-images.githubusercontent.com/73120647/96462724-83bb2980-11eb-11eb-9f9e-025977609af1.png)

**Comment by joelwetzel** [comment]
Thanks for the report.  I've posted a bug fix.  However, if your lock is z-wave and is regularly not reporting physical events back to the hub, I would recommend looking into changing the chipset over to Zigbee.

**Comment by joelwetzel** [comment]
Closed

**Comment by macdenewf** [comment]
Thanks for the fix.  Regards
Mac
